### PR TITLE
Adds z-index to particles to ensure they are always in front

### PR DESCRIPTION
**Pull request by mikowl**
I had a project where I could not get the particles to be in front of my fixed div, this will ensure particles are always in front.

### CODE REVIEW

**Comment by herrethan** [comment]
@mikowl, sigh, I was hoping we wouldn't have to go down this path (what happens when the next user needs '9999' for example?). 

What do you think about selectively passing a `zIndex` style prop, if found, on the `screen.container` element, down to the `classes.screen` element. Because presumably, a `zIndex` on the `screen.container` has no effect anyway.

**Comment by mikowl** [comment]
@herrethan That works, I've updated the branch to your suggestions, let me know if I understood you correctly

**Comment by herrethan** [comment]
@mikowl since I can't fork your branch, created a new one here, this is more specifically what I was thinking:
https://github.com/herrethan/react-confetti-explosion/pull/16

**Comment by herrethan** [comment]
[Merged](https://github.com/herrethan/react-confetti-explosion/pull/16) and published!

**Pull request closed without merging**
